# Generated by Django 4.1.2 on 2022-11-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='catalog.ItemInOrder', to='catalog.product'),
        ),
    ]
