# Generated by Django 4.1.2 on 2022-10-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержденный'), ('canceled', 'Отмененный')], default='new', max_length=254, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
    ]
