# Generated by Django 4.1.2 on 2022-10-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_applications_status_alter_applications_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('new', '«Новая»'), ('confirmed', 'Принято в работу'), ('canceled', 'Выполнено')], default='new', max_length=254, verbose_name='Статус'),
        ),
    ]
