# Generated by Django 4.1.2 on 2022-11-15 04:58

import catalog.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_order_count_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commented',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='imageses',
            field=models.ImageField(blank=True, upload_to=catalog.utilities.get_timestamp_path, verbose_name=' Доп Изображение'),
        ),
    ]
