# Generated by Django 4.1.2 on 2022-11-14 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_iteminorder_count_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.order', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='iteminorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='каталог'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Принято в работу'), ('canceled', 'Выполнено')], default='new', max_length=254, verbose_name='Статус'),
        ),
    ]
