# Generated by Django 4.1.2 on 2022-11-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_iteminorder_order_alter_iteminorder_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminorder',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
