# Generated by Django 4.1.2 on 2022-11-15 07:10

import catalog.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_iteminorder_product_remove_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='imageses',
            field=models.ImageField(blank=True, default='', upload_to=catalog.utilities.get_timestamp_path, verbose_name=' Доп Изображение'),
        ),
    ]
