# Generated by Django 4.1.2 on 2022-11-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_order_imageses'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='counter',
            field=models.IntegerField(blank=True, null=True, verbose_name='счетчик'),
        ),
    ]
