# Generated by Django 4.1.2 on 2022-11-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_order_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='order',
            name='descriptions',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
    ]
