# Generated by Django 4.1.2 on 2022-11-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_order_rejection_reason_order_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Принято в работу'), ('canceled', 'Выполнено')], default='new', max_length=254, verbose_name='Статус'),
        ),
    ]
