# Generated by Django 4.1.2 on 2022-11-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
    ]
